### ISSUE TITLE
pleaseee

### ISSUE THREAD

**Issue by DonaldDuckyy** [TeamCLIU/ZRLockerPresets#1]
can you please make a youtube video on how to do it specifically, it would mean alot of help

**Comment by creaffy** [comment]
I will soon, I am currently working on a much better version of this project that will include user UI and will be much more user friendly:) You can add me on discord (creaffy#1939) and I will let you know once I'm done with the newer version

**Comment by DonaldDuckyy** [comment]
> 

i have added you my tags are donald#7639
